version: "3.9"
services:
  app:
    build: .
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      HARDHAT_HOST: chain
  chain:
    build: .
    command: sh -c "yarn chain"
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - .:/app
  deploy:
    build: .
    command: sh -c "yarn deploy"
    ports:
      - "3002:3002"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      HARDHAT_HOST: chain